### ISSUE TITLE
Performance tuning checklist

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#1542]
- [ ] `lib.wc.isSpace` can be memoized
- [x] `hterm.getClientWidth(this.screen_)` gets called too many times and forces layout sometimes.
  - This is used to measure scrollbar width, but if I'm not mistaken, it should always be 0 for us since we have floating scrollbars?
- [x] RPC for pty data could be string based instead of object based
- [ ] DOM element pooling

**Comment by Stanzilla** [comment]
@rauchg care to update that issue to current state?

**Comment by albinekb** [comment]
This issue can be closed, all of the listed improvements were for hterm  👍
