### ISSUE TITLE
Create beta release channel

### ISSUE THREAD

**Issue by albinekb** [zeit/hyper#1925]
#### Todo
- [ ] Implement new `about` window (with info about release and a button to check for updates)
- [ ] Configure electron-builder with stable.json and beta.json configs
- [ ] Set up automatic builds+release uploading
- [x] Hyper Beta.app icon @CodeTheory 🕶 
- [ ] Update website with information about Hyper Beta

We will do this the same way Atom, Chrome, VSCode etc does it: Have a separate appId (Hyper Beta.app) so that you can run stable and beta side by side.

<hr />

Documentation for [`autoUpdater`](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md#autoupdatersetfeedurlurl-requestheaders)

_Anyone got experience with building nightlys/releases of electron via travis? raise your hand!_

<hr />

<details>
<summary>Blah blah blah</summary>

-  Let users choose release channel [stable, beta]
-  Should be built and released every night (or so)
- Probably a good idea to tag them with the date, so that if a nightly breaks, you can easily roll back to the previous one.
- More users running the latest code, let's us see regressions/bugs more quickly
- Fixes released faster (current releases is ~1-2 months apart)
- [Shipping is the heartbeat](https://blog.intercom.com/shipping-is-your-companys-heartbeat/) - I think one reason for all the stale PR's is that the releases is moving too slow, this would change that and hopefully make people more motivated to work on hyper! (I will!)

</details>

**Comment by pchomik** [comment]
Great idea. To use hyper I had to build it manually on my machine.

**Comment by rauchg** [comment]
+1

**Comment by Stanzilla** [comment]
info about the release branch can probably be added as part of https://github.com/zeit/hyper/pull/1826?

**Comment by CodeTheory** [comment]
Working on the beta logo. 
We also discussed that the beta channel app should be named "Hyper Early". Which is awesome 😎

**Comment by ppot** [comment]
@albinekb So :D

**Comment by CodeTheory** [comment]
I believe we can close this now! 
And icon is to follow when you set the beta release channel but you can now set it via the `.hyper.js` by adding `updateChannel: 'canary'` to it.

Gif here: https://twitter.com/rauchg/status/902970586699259904
